name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.5.1

    - name: Install dependencies
      run: |
        poetry install --no-interaction --no-ansi


    - name: Run flake8
      run: |
        poetry run flake8 app/modules/voting/ --count --show-source --statistics