name: CI Pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    env:
      DATABASE_URL: sqlite:///./sqr_voting.db
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      REFRESH_TOKEN_EXPIRE_DAYS: 7

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Clean Poetry environments
      run: |
        rm -rf ~/.poetry || true
        rm -rf ~/.cache/pypoetry || true
        rm -rf ~/.local/share/pypoetry || true
        rm -rf ~/.config/pypoetry || true
        rm -rf .venv || true
        mkdir -p ~/.config/pypoetry

    - name: Install Poetry
      run: |
        pip install poetry==1.5.1 --user
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Configure Poetry
      run: |
        poetry config virtualenvs.in-project true

    - name: Install dependencies
      run: |
        poetry install --no-interaction --no-ansi --with dev

    - name: Run tests with Poetry
      run: |
        poetry run pytest app/tests -v

    - name: Check PEP-8 style with flake8
      run: |
        poetry run flake8 app/ --count --show-source --statistics --max-line-length=88

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: ${{ github.ref == 'refs/heads/main' }}
        tags: |
          ${{ secrets.DOCKER_HUB_USERNAME }}/sqr-voting-system:latest
          ${{ secrets.DOCKER_HUB_USERNAME }}/sqr-voting-system:${{ github.sha }}
